# Generated by Django 4.2.1 on 2023-05-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lock',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile-photos')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='background-photos')),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_lock', models.BooleanField(default=False)),
                ('follower', models.ManyToManyField(blank=True, null=True, to='accountapplication.profile')),
                ('following', models.ManyToManyField(blank=True, null=True, to='accountapplication.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
