# Generated by Django 4.1.7 on 2023-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_media',
            field=models.FileField(blank=True, null=True, upload_to='post-images'),
        ),
    ]
