# Generated by Django 4.1.7 on 2023-03-26 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0002_alter_post_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
