# Generated by Django 4.1.7 on 2023-03-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0003_alter_post_like_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
