# Generated by Django 4.1.7 on 2023-03-31 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0004_remove_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_media',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
