# Generated by Django 4.1.7 on 2023-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapplication', '0005_remove_comment_comment_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
